### ISSUE TITLE
Add OCTO to tokenlist

### ISSUE THREAD

**Issue by nathanjessen** [magnet-finance/magnet-app#38]
We'd like to create Sablier streams using your UI.

Please add support for OCTO.

**Comment by willhennessy** [comment]
Thanks for trying magnet Nathan! Really appreciate the PR. I've just merged it to dev and release branch. It should be live now.

Sometimes CloudFront caches the old version of the site, so try hard reloading if you don't see it right away.

**Comment by nathanjessen** [comment]
I appreciate the quick response. However, I've tried the app in multiple browsers with a hard reload and completely clearing my browser cache but the token doesn't appear in the dropdown. I'll check again in a few hours but I think something might be missing in the deploy.

**Comment by ggranito** [comment]
Hmm, I checked on my computer and saw it listed. I can look into the AWS
caching tomorrow

**Comment by nathanjessen** [comment]
The OCTO token is now showing up in the list. So in that regard, the issue is complete.

I tried creating a stream though and I'm seeing errors in the console for the gnosis safe relay. I'll investigate and open an Issue when it's a little more clear.

**Comment by ggranito** [comment]
Are you on the multisig? Gnosis doesn't let people who aren't propose new
transactions

**Comment by nathanjessen** [comment]
Yes I'm on the multisig and connected using that wallet. My initial findings leads me to believe that getGasEstimate should include `safe: safeAddress,` in the request. But even after that change, I'm seeing other Network errors. Still diving into it.
